<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MSI" ignored="0" name="ItestListeners" tests="8" failures="1" timestamp="2022-12-24T20:03:04 IST" time="0.041" errors="0">
  <testcase name="testMethod" time="0.005" classname="TestNG.ITestListenersWithExample"/>
  <testcase name="testMethod2" time="0.0" classname="TestNG.ITestListenersWithExample">
    <failure type="java.lang.AssertionError" message="expected [11] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [11] but found [10]
at TestNG.ITestListenersWithExample.testMethod2(ITestListenersWithExample.java:22)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testMethod2 -->
  <testcase name="testMethod3" time="0.0" classname="TestNG.ITestListenersWithExample">
    <skipped/>
  </testcase> <!-- testMethod3 -->
  <testcase name="testMethod4" time="0.0" classname="TestNG.ITestListenersWithExample"/>
  <testcase name="testMethod4" time="0.0" classname="TestNG.ITestListenersWithExample"/>
  <testcase name="testMethod4" time="0.0" classname="TestNG.ITestListenersWithExample"/>
  <testcase name="testMethod4" time="0.0" classname="TestNG.ITestListenersWithExample"/>
  <testcase name="testMethod4" time="0.0" classname="TestNG.ITestListenersWithExample"/>
</testsuite> <!-- ItestListeners -->
